### ISSUE TITLE
Feature request: VTF format options

### ISSUE THREAD

**Issue by Jofoyo** [koerismo/PBR-2-Source#13] opened 2024-10-04 15:27 UTC
Presently all textures will use uncompressed formats, however this is very debilitating in file size, having options at least to switch formats per texture is very desirable. Presently if using this I would absolutely need to manually do reconversions for sane file sizes.

DXT1 compression is very unnoticeable on albedos most of the time, especially at higher resolutions, and uncompressed is very overkill here. Modern day games still use DXT compression on albedos. DXT5 offers DXT RGB but uncompressed alpha and works great if it contains an envmapmask. If implementation is an issue you can see VTFEdit Reloaded for an updated compression binary from AMD.

Most of the channels in the phongexponent texture will go unused, and having just an I8 format would work here in a lot of cases. BGRX5551 and IA88 are also decent compromises in their own circumstances.

**Comment by koerismo** [comment] 2024-10-06 04:43
Hi, this is actually a regression! Basetextures should be compressed by default, and bumpmaps left uncompressed. The library I use (srctools) does have this behavior implemented, however it is just not exposed through the image adapter currently.

**Comment by koerismo** [comment] 2024-10-17 18:08
This should be addressed in the next update. The basetexture should use DXT1/5 and the bumpmap should use RGB/A8. The phong exponent should only use I8, since the phong saturation feature doesn't really seem to do much (or even exist) in the games i've tested.

**Closed by koerismo** 2024-10-17 18:08 UTC
Labels: bug
